### ISSUE TITLE
Requirement is pinned for numato-gpio 0.7.1: pyserial==3.1.1

### ISSUE THREAD

**Issue by MartinHjelmare** [clssn/numato-gpio#4]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by clssn** [comment]
Released numato-gpio 0.8.0 relaxing pyserial to >=3.1.1. Update PR on home-assistant/core is under review: https://github.com/home-assistant/core/pull/38415

**Comment by MartinHjelmare** [comment]
Thanks!
